- name: "adding bridge-nf module"
  shell: modprobe br_netfilter
  become: true

- name: "adding sysctl net.ipv4.ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  become: true

- name: "adding sysctl net.bridge.bridge-nf-call-iptables"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes
  become: true

- name: "adding sysctl ipv6 forwarding"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: yes
  when: ipv6_enabled
  become: true

- name: "adding sysctl ip6tables for intra-bridge"
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes
  when: ipv6_enabled
  become: true

- name: "setting net.core.somaxconn for redis"
  sysctl:
    name: net.core.somaxconn
    value: '16000'
    state: present
    reload: yes
  become: true

- name: "setting transparent_hugepage to never"
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
  become: true

- name: "install python3-pip"
  apt:
    name: "python3-pip"
    update_cache: yes
    force: yes
  become: true

- name: "install boto3"
  pip:
    name: "boto3"
  become: true

- name: "swapp off"
  shell: swapoff -a
  become: true